#!/usr/bin/env bash

VERSION=$1 
shift
PREFIX=$PGSQLENV_VERSION_INSTALL_DIR/$VERSION
PGCONF=$PREFIX/data/postgresql.conf
PSQL=$PREFIX/bin/psql

if [ -e $PGCONF ]
then
           PGPORT=`egrep '^#?port\s*=' $PGCONF  | perl -pe 's/^#?port\s*=\s*(\d+).*$/$1/;'`
	   $PSQL -p $PGPORT $* || echo $VERSION : Not Running?
else
        echo "$VERSION : Not initalized"
fi


