#!/usr/bin/env bash
if [ "$FLAG_ALL" = "1" ]; 
then
VALS=`ls -1 $PGSQLENV_VERSION_INSTALL_DIR`
else
VALS=$1
fi

for i in $VALS
do
PREFIX=$PGSQLENV_VERSION_INSTALL_DIR/$i
export PGDATA=$PREFIX/data
PGCONF=$PGDATA/postgresql.conf
PGCTL=$PREFIX/bin/pg_ctl

printf '%-8s : \n' $i
if [ -x $PGCTL ]
then
    if [ -d $PGDATA ] 
    then
	echo PGDATA=$PGDATA
	echo PGPORT=`(egrep '^#?port\s*=' $PGCONF  | perl -pe 's/^#?port\s*=\s*(\d+).*$/$1/;' ) || echo 5432` 
    else
        echo "Not initialized"
    fi
else
	echo "Not installed"
fi

done
