#!/usr/bin/env bash

if [ "$FLAG_ALL" = "1" ];
then
VALS=`ls -1 $PGSQLENV_VERSION_INSTALL_DIR`
else
VALS=$1
fi

for i in $VALS
do
PREFIX=$PGSQLENV_VERSION_INSTALL_DIR/$i
CREATEUSER=$PREFIX/bin/createuser
CREATEDB=$PREFIX/bin/createdb
PGCONF=$PREFIX/data/postgresql.conf
PSQL=$PREFIX/bin/psql

echo -n $i ":  "
if [ -e $PGCONF ]
then
        ( 
           PGPORT=`egrep '^#?port\s*=' $PGCONF  | perl -pe 's/^#?port\s*=\s*(\d+).*$/$1/;'`
	   ( $PSQL -q  -p $PGPORT -t -c "select 'OK'" postgres | sed -e '/^$/d') || (
	   $CREATEUSER -p $PGPORT -s `whoami`
	   $CREATEDB -p $PGPORT
	   echo DONE 
	  ) 
         ) || echo FAILED
else
        echo "Not initalized"
fi

done

