#!/usr/bin/env bash

if [ "$FLAG_ALL" = "1" ];
then
VALS=`ls -1 $PGSQLENV_VERSION_INSTALL_DIR`
else
VALS=$1
fi

for i in $VALS
do
PREFIX=$PGSQLENV_VERSION_INSTALL_DIR/$i
CREATEUSER=$PREFIX/bin/createuser
CREATEDB=$PREFIX/bin/createdb
PGCONF=$PREFIX/data/postgresql.conf
PSQL=$PREFIX/bin/psql

echo -n $i ":  "
if [ -e $PGCONF ]
then
        ( 
           PGPORT=`egrep '^#?port\s*=' $PGCONF  | perl -pe 's/^#?port\s*=\s*(\d+).*$/$1/;'`
	   ( $PSQL -q -p $PGPORT -t -c "select 'OK'" 2>/dev/null) || (
	   $CREATEUSER -p $PGPORT -s `whoami` 2>/dev/null 
	   $CREATEDB -p $PGPORT 2>/dev/null 
	   echo DONE 2>/dev/null 
	  ) | sed -e 's/^$//' 
         ) || echo FAILED
else
        echo "Not initalized"
fi

done

